// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// schaefer_cmsy
List schaefer_cmsy(NumericVector r_lim, NumericVector k_lim, double sig_r, NumericVector startbio, NumericVector yr, NumericVector ct, int interyr_index, NumericVector interbio, int reps, NumericVector finalbio);
RcppExport SEXP datalimited_schaefer_cmsy(SEXP r_limSEXP, SEXP k_limSEXP, SEXP sig_rSEXP, SEXP startbioSEXP, SEXP yrSEXP, SEXP ctSEXP, SEXP interyr_indexSEXP, SEXP interbioSEXP, SEXP repsSEXP, SEXP finalbioSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type r_lim(r_limSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type k_lim(k_limSEXP);
    Rcpp::traits::input_parameter< double >::type sig_r(sig_rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type startbio(startbioSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type yr(yrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ct(ctSEXP);
    Rcpp::traits::input_parameter< int >::type interyr_index(interyr_indexSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type interbio(interbioSEXP);
    Rcpp::traits::input_parameter< int >::type reps(repsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type finalbio(finalbioSEXP);
    __result = Rcpp::wrap(schaefer_cmsy(r_lim, k_lim, sig_r, startbio, yr, ct, interyr_index, interbio, reps, finalbio));
    return __result;
END_RCPP
}
// comsir_effort
double comsir_effort(double a, double x, double k, double bt);
RcppExport SEXP datalimited_comsir_effort(SEXP aSEXP, SEXP xSEXP, SEXP kSEXP, SEXP btSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type bt(btSEXP);
    __result = Rcpp::wrap(comsir_effort(a, x, k, bt));
    return __result;
END_RCPP
}
// comsir_bounds
Rcpp::NumericMatrix comsir_bounds(NumericVector x_bounds, NumericVector a_bounds, NumericVector k_bounds, NumericVector effort_bounds, int nsim, bool dampen);
RcppExport SEXP datalimited_comsir_bounds(SEXP x_boundsSEXP, SEXP a_boundsSEXP, SEXP k_boundsSEXP, SEXP effort_boundsSEXP, SEXP nsimSEXP, SEXP dampenSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x_bounds(x_boundsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a_bounds(a_boundsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type k_bounds(k_boundsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type effort_bounds(effort_boundsSEXP);
    Rcpp::traits::input_parameter< int >::type nsim(nsimSEXP);
    Rcpp::traits::input_parameter< bool >::type dampen(dampenSEXP);
    __result = Rcpp::wrap(comsir_bounds(x_bounds, a_bounds, k_bounds, effort_bounds, nsim, dampen));
    return __result;
END_RCPP
}
// check_comsir_lik
NumericVector check_comsir_lik(int nsim, NumericVector predbio, NumericVector predprop, NumericVector like);
RcppExport SEXP datalimited_check_comsir_lik(SEXP nsimSEXP, SEXP predbioSEXP, SEXP predpropSEXP, SEXP likeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type nsim(nsimSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type predbio(predbioSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type predprop(predpropSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type like(likeSEXP);
    __result = Rcpp::wrap(check_comsir_lik(nsim, predbio, predprop, like));
    return __result;
END_RCPP
}
// posfun
NumericMatrix posfun(NumericVector x, double eps);
RcppExport SEXP datalimited_posfun(SEXP xSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    __result = Rcpp::wrap(posfun(x, eps));
    return __result;
END_RCPP
}
// effortdyn
NumericMatrix effortdyn(NumericVector h, NumericVector k, NumericVector r, NumericVector x, NumericVector a, NumericVector yr, NumericVector ct, bool logistic_model);
RcppExport SEXP datalimited_effortdyn(SEXP hSEXP, SEXP kSEXP, SEXP rSEXP, SEXP xSEXP, SEXP aSEXP, SEXP yrSEXP, SEXP ctSEXP, SEXP logistic_modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type h(hSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type yr(yrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ct(ctSEXP);
    Rcpp::traits::input_parameter< bool >::type logistic_model(logistic_modelSEXP);
    __result = Rcpp::wrap(effortdyn(h, k, r, x, a, yr, ct, logistic_model));
    return __result;
END_RCPP
}
