# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Schaefer production model for catch-MSY method
#'
#' @param r_lim Numeric vector of lower and upper intrinsic population growth
#'   rates
#' @param k_lim Numeric vector of lower and upper carrying capacities
#' @param sig_r Standard deviation of process noise
#' @param startbt A vector of possible starting biomasses to loop over
#' @param yr Numeric vector of years
#' @param ct Numeric vector of catch
#' @param interyr_index Index of the interim year within time series for which
#'   biomass estimate is available
#' @param interbio_lim A numeric vector that gives the lower and upper biomass
#'   limits in the interim year
#' @param prior_log_mean Prior log mean
#' @param prior_log_sd Prior log sd
#' @param reps Number of repititions
#'
#' @useDynLib datalimited
#' @importFrom Rcpp sourceCpp
#' @export
#'
#' @references
#' Martell, S., & Froese, R. (2013). A simple method for estimating MSY from
#' catch and resilience. Fish and Fisheries, 14(4), 504-514.
#' \url{http://doi.org/10.1111/j.1467-2979.2012.00485.x}
#'
#' @examples
#' schaefer_cmsy(c(0.1, 0.3), c(80, 100), sig_r = 0.1,
#'   startbt = seq(0.2, 0.6, by = 0.05), yr = 1:10, ct = rnorm(10),
#'   prior_log_mean = 0.3, prior_log_sd = 0.1, interyr_index = 2,
#'   interbio_lim = c(0, 1), reps = 10L)
schaefer_cmsy <- function(r_lim, k_lim, sig_r, startbt, yr, ct, interyr_index, prior_log_mean, prior_log_sd, interbio_lim, reps) {
    .Call('datalimited_schaefer_cmsy', PACKAGE = 'datalimited', r_lim, k_lim, sig_r, startbt, yr, ct, interyr_index, prior_log_mean, prior_log_sd, interbio_lim, reps)
}

