# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @param r_lim Numeric vector of lower and upper intrinsic population growth
#'   rates
#' @param k_lim Numeric vector of lower and upper carrying capacities
#' @param startbio A vector of possible starting biomasses to loop over
#'
#' @useDynLib datalimited
#' @importFrom Rcpp sourceCpp
#' @export
#' @rdname cmsy
schaefer_cmsy <- function(r_lim, k_lim, sig_r, startbio, yr, ct, interyr_index, prior_log_mean, prior_log_sd, interbio, reps) {
    .Call('datalimited_schaefer_cmsy', PACKAGE = 'datalimited', r_lim, k_lim, sig_r, startbio, yr, ct, interyr_index, prior_log_mean, prior_log_sd, interbio, reps)
}

